import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  navbar,
  postForm,
  auth,
}: Readonly<{
  children: React.ReactNode;
  navbar: React.ReactNode;
  postForm: React.ReactNode;
  auth: React.ReactNode;
}>) {
  const [showModal, setShowModal] = useState(false);
  return (
    <html lang="en">
      <body className={inter.className}>
        {navbar}
        {auth}
        {showModal &&
          <div className="fixed inset-0 bg-black bg-opacity-50 flex justify-center items-center">
            <div className="bg-white p-4">
              {postForm}
            </div>
          </div>
        }
        {children}
      </body>
    </html>
  );
}
